# Linux makefile

legkisebbszam: legkisebbszam.c lksz.h
    gcc -o legkisebbszam legkisebbszam.c

lkszkliens: kliens.c lksz.h
    gcc -o legkisebbszam legkisebbszam.c

all: legkisebbszam lkszkliens

.PHONY: all